---
title: "Program Day 1"
---

### January 6 (Thursday)

```{r include=FALSE}
require(knitr)
require(kableExtra)
require(dplyr)
# rmarkdown::render_site()
```

```{r echo=FALSE, include=TRUE}
session_title <- c(
  "Session 1: Welcome Address",
  "Break",
  "Session 2: Causal Inference and Big Data",
  "Break",
  "Section 3: Causal Inference in Time Series Cross Sectional Data",
  "Break",
  "Section 4: Text Analysis"
)
  
session_time <- c(
  "9:00–10:30 am",
  "10:30-10:40 am",
  "10:40-12:10 pm",
  "12:10–1:00 pm",
  "1:00–2:30 pm",
  "2:30-2:45 pm",
  "2:45-4:15 pm"
)

session_zoom <- c(
  rep("https://zoom.us/", length(session_time))
)

section_header <- fun_section_header(session_title, settion_time, session_zoom)


event_name <- c(
  "Welcome Address by SPM President Betsy Sinclair",  # 1
  "Round Table: _Past, Present, and Future of Political Methodology._\n
   **Panelist**: Molly Roberts, Yiqing Xu, Betsy Sinclair",  # 2
  "Break",  # 3
  "Chad Hazlett and Yiqing Xu.\n
  _Trajectory Balancing: A kernel based weighting approach to causal inference with time-series cross-sectional data._",  # 4
  "Daniel J. Hopkins, Yphtach Lelkes, Samuel Wolken.\n
  _Which News Goes Viral? Measuring Identity Threats and Engagement with News Media Posts on Twitter and Facebook._",  # 5
  "Discussant: Xun Pang (Tsinghua University)",  # 6
  "Lunch Break",   # 7
  "Ye Wang, Yiqing Xu, Junlong Aaron Zhou.\n
  _Regression Discontinuity Designs for High-frequency Time-Series Cross-Sectional Data._",  # 8
  "Licheng Liu and Xun Pang.\n
  _Causal Inferences with Time-Series Cross-Sectional Data under Spatial Interference and Interdependence: A Model-based Approach._",  # 9
  "Discussant: Joon Seok Yang (Sungkyunkwan University)",  # 10
  "Break",  # 11
  "Han Zhang and Haoran Liang.\n
  _Joint Text-and-Image Clustering for Social Science Research._",  # 12
  "Fang-Yi Chiou and Max Goplerud.\n
  _Measuring and Theorizing the Legislative Records of Members of the United States Congress, 1873-2010._",  # 13
  "Discussant: Yunkyu Sohn (Seoul National University)" # 14
)

paper_link <- c(
  "",  # 1
  "",  # 2
  "",  # 3
  "",  # 4
  "",  # 5
  "",  # 6
  "",  # 7
  "",  # 8
  "",  # 9
  "",  # 10
  "",  # 11
  "",  # 12
  "",  # 13
  ""   # 14
)

events <- if_else(
  paper_link != "",
  paste0(event_name, " ", "([paper](", paper_link, "))"),
  event_name
)

schedule_tab <- tibble(
  Time = c(
    rep(section_header[1], 2), 
    section_header[2], 
    rep(section_header[3], 3), 
    section_header[4],
    rep(section_header[5], 3), 
    section_header[6], 
    rep(section_header[7],3)),
  Time_fill = rep("", length(events)),
  Time_start = c(
    "9:00 am-", "9:45 am-",
    "", 
    "10:40 am-", "11:10 am-", "11:40 am-",
    "",
    "1:00 pm-", "1:30 pm-", "2:00 pm-",
    "",
    "2:45 pm-", "3:15 pm-", "3:45 pm-"
  ),
  Events = events
) 

schedule_tab %>% 
  select(Time_start, Events) %>% 
  kable(col.names = NULL) %>% 
    kable_styling(full_width = TRUE, font_size = 20) %>% 
    column_spec(1, bold = FALSE) %>% 
    column_spec(2, 
                background = c(
                  rep("#2c3e50", 2), 
                  "#BCC5C5", 
                  rep("#E5E5E5", 3),
                  "#BCC5C5", 
                  rep("#E5E5E5", 3),
                  "#BCC5C5", 
                  rep("#E5E5E5", 3)
                  ),
                color = c(
                  rep("white", 2), 
                  "white", 
                  rep("black", 3),
                  "white", 
                  rep("black", 3),
                  "white", 
                  rep("black", 3)
                  )) %>% 
    pack_rows(
      index = table(forcats::fct_inorder(schedule_tab$Time)),
      label_row_css = "border-bottom: 3.5px solid;",
    ) %>%
  column_spec(1, width = "7em") 
```

